---
#  tasks:
- name: Baixar o instalador do Zabbix Agent
  win_get_url:
    url: https://repo.zabbix.com/zabbix/5.4/windows/x86_64/zabbix_agent-5.4.0-windows-amd64-openssl.msi
    dest: C:\Temp\zabbix_agent.msi

- name: Instalar o Zabbix Agent
  win_command: msiexec /i "C:Users\Administrator\Downloads\zabbix_agent.msi" /qn^ SERVER=10.10.2.10
  
- name: Copiar template zabbix agent
  win_template:
    src: zabbix_agentd.conf
    dest: 'C:\Program Files\Zabbix Agent\zabbix_agentd.conf' 
    
- name: Restart a service
  win_service:
    name: Zabbix Agent
    state: restarted
        
