---
#  tasks:
- name: Baixar o instalador do Zabbix Agent
  win_get_url:
    url:  https://cdn.zabbix.com/zabbix/binaries/stable/6.2/6.2.7/zabbix_agent-6.2.7-windows-amd64-openssl.msi 
    dest: C:\Users\Administrator\Downloads\zabbix_agent.msi

- name: Instalar o Zabbix Agent
  win_package:            
    path: C:\Users\Administrator\Downloads\zabbix_agent.msi                      
    arguments: '/qn SERVER=10.10.2.10'

- name: Copiar template zabbix agent
  win_template:
    src: zabbix_agentd.conf
    dest: 'C:\Program Files\Zabbix Agent\zabbix_agentd.conf' 
    
- name: Restart a service
  win_service:
    name: Zabbix Agent
    state: restarted
        
